// CIWA-B
export const B_LABELS = {
    b1:{labels:['Ikke i det hele tatt','Litt','Moderat','Mye', 'Veldig mye'], max:4},
    b2:{labels:['Ikke i det hele tatt','','','', 'Ute av stand til å fungere'], max:4},
    b3:{labels:['Ikke i det hele tatt','','','', 'Veldig mye'], max:4},
    b4:{labels:['Ikke i det hele tatt','','','', 'Ute av stand til å konsentrere seg'], max:4},
    b5:{labels:['Ikke i det hele tatt','','','', 'Ingen appetitt, klarer ikke å spise'], max:4},
    b6:{labels:['Ikke i det hele tatt','','','', 'Intens brenning/nummenhet'], max:4},
    b7:{labels:['Ikke i det hele tatt','','','', 'Konstant banking'], max:4},
    b8:{labels:['Ikke i det hele tatt','','','', 'Konstant hodepine'], max:4},
    b9:{labels:['Ikke i det hele tatt','','','', 'Veldig «støle» og smertefulle'], max:4},
    b10:{labels:['Ikke i det hele tatt','','','', 'Veldig engstelig'], max:4},
    b11:{labels:['Ikke i det hele tatt','','','', 'Veldig opprørt'], max:4},
    b12:{labels:['Meget avslappet','', 'Moderat','', 'Ikke i det hele tatt'], max:4},
    b13:{labels:['Ikke i det hele tatt','','','', 'Veldig svak'], max:4},
    b14:{labels:['Absolutt nok søvn','','','', 'Ikke i det hele tatt'], max:4},
    b15:{labels:['Ikke i det hele tatt','','','', 'Meget sensitiv for lys, uklart syn'], max:4},
    b16:{labels:['Ikke i det hele tatt','','','', 'Veldig redd'], max:4},
    b17:{labels:['Ikke i det hele tatt','','','', 'Veldig bekymret'], max:4},
    b18:{labels:['Ingen, normal aktivitet','','Rastløs','', 'Går frem og tilbake, klarer ikke å sitte stille'], max:4},
    b19:{labels:['Ingen tremor','Ingen synlig tremor, men den kan kjennes fingertupp mot fingertupp','Synlig tremor, men mild','Moderat tremor når armene er utstrakt','Sterk synlig tremor selv om armene ikke er utstrakt'], max:4},
    b20:{labels:['Ingen synlig svette','Knapt merkbar svette, klamme håndflater','Klam håndflate og panne. Pas rapporterer svette i armhuler','Tydelige svetteperler i panne','Alvorlig, gjennomvåt av svette'], max:4}
};
export const CIWA_B = [
    { key:'b1', title:'Føler du deg irritabel?', max:4 },
    { key:'b2', title:'Føler du deg trett?', max:4 },
    { key:'b3', title:'Føler du deg anspent?', max:4 },
    { key:'b4', title:'Har du konsentrasjonsvansker?', max:4 },
    { key:'b5', title:'Har du nedsatt matlyst?', max:4 },
    { key:'b6', title:'Har du en følelse av nummenhet eller en brennende følelse i ansikt, hender eller føtter?', max:4 },
    { key:'b7', title:'Har du hjertebank?', max:4 },
    { key:'b8', title:'Har du hodepine?', max:4 },
    { key:'b9', title:'Føles musklene «støle» eller smertefulle?', max:4 },
    { key:'b10', title:'Føler du deg engstelig, nervøs eller rastløs?', max:4 },
    { key:'b11', title:'Føler du deg opprørt?', max:4 },
    { key:'b12', title:'Hvor avslappet/rolig var søvnen din siste natt?', max:4 },
    { key:'b13', title:'Føler du deg svak?', max:4 },
    { key:'b14', title:'Tror du at du ikke fikk nok søvn siste natt?', max:4 },
    { key:'b15', title:'Har du synsproblemer (overfølsom for lys, uklart syn)', max:4 },
    { key:'b16', title:'Er du redd/engstelig?', max:4 },
    { key:'b17', title:'Har du bekymret deg for mulige ulykker/uhell i det siste?', max:4 },
    { key:'b18', title:'Klinisk observasjon: Rastløshet/uro', max:4 },
    { key:'b19', title:'Klinisk observasjon: Tremor', max:4 },
    { key:'b20', title:'Klinisk observasjon: Svette', help:'Kjenn på håndflatene', max:4 }
];